### ISSUE TITLE
[FEATURE] Add support for model extending.

### ISSUE THREAD

**Issue by dannysmc95** [dannysmc95/rewyre#9]
### Describe a summary of your feature and what it will do.
As part of the plugin development, I want to allow models to be extended by plugins, alongside more uses for the model type.

So if you have 2 models that are using the `user` type, then it would be pretty useful to specify a way to add new properties. At the moment, plugins will be able to add lots of new features, including things like controllers, therefore if you want to create a plugin to support Discord oAuth2 support (which is done on one of my projects using rewyre) then I would be able to externalise that code, but the issue is I don't think a user wants a whole new model specifically for that functionality but instead extend all user models to add support for that, then each plugin can come with settings to handle different behaviour.

### Describe the solution you'd like.
The best way I see this working is something like:

```typescript
/*
	Firstly let's define our main model.
*/
import { Model, AbstractModel, Extend, Ignore } from 'framework';

@Model('users', 'user', {
	username: 'string',
	password: 'string',
	email: 'string',
})
export class UsersModel extends AbstractModel {}

/*
	Now let's define our extend method.
*/
@Extend('user')
@Ignore(['username', 'password'])
@Model('extend_user_discord', 'user', {
	username: 'string',
	password: 'string',
	discord_token: 'string',
})
export class UsersModel extends AbstractModel {}
```

Now to note:

* The Extend decorator is a generic decorator, can be used to extend many things (providers, services, models, etc).
* The extending model can be used as a normal model still, you can use the `@Ignore` decorator to ignore certain properties, or methods, depending on what you're extending.
* Specifically regarding models, when a base model is extended by an extending model, all properties will be added as optional, if you want to use what is defined in the extending model (not suggested in existing code bases) then the optional parameter can be passed as true to the extend decorator like so: `@Extend('user', true)`.

**Comment by deathlynocturnal** [comment]
Project is deprecated, in favour of @sodacore/core project.
